/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace RockPaperScissors {
  export type GameStruct = {
    player1: AddressLike;
    player2: AddressLike;
    betAmount: BigNumberish;
    player1Move: BigNumberish;
    player2Move: BigNumberish;
    status: BigNumberish;
    createdAt: BigNumberish;
    expiresAt: BigNumberish;
  };

  export type GameStructOutput = [
    player1: string,
    player2: string,
    betAmount: bigint,
    player1Move: bigint,
    player2Move: bigint,
    status: bigint,
    createdAt: bigint,
    expiresAt: bigint
  ] & {
    player1: string;
    player2: string;
    betAmount: bigint;
    player1Move: bigint;
    player2Move: bigint;
    status: bigint;
    createdAt: bigint;
    expiresAt: bigint;
  };
}

export interface RockPaperScissorsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "FEE_BPS"
      | "cancel"
      | "claimTimeout"
      | "defaultTimeout"
      | "feePool"
      | "getGame"
      | "maxBet"
      | "minBet"
      | "owner"
      | "renounceOwnership"
      | "setDefaultTimeout"
      | "submitMove"
      | "transferOwnership"
      | "withdrawFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeesWithdrawn"
      | "GameCancelled"
      | "GameDraw"
      | "GameOpened"
      | "GameSettled"
      | "GameTimedOut"
      | "MoveSubmitted"
      | "OwnershipTransferred"
      | "TimeoutUpdated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "FEE_BPS", values?: undefined): string;
  encodeFunctionData(functionFragment: "cancel", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "claimTimeout",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "defaultTimeout",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "feePool", values?: undefined): string;
  encodeFunctionData(functionFragment: "getGame", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "maxBet", values?: undefined): string;
  encodeFunctionData(functionFragment: "minBet", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setDefaultTimeout",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitMove",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "FEE_BPS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cancel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "defaultTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feePool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getGame", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "maxBet", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "minBet", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDefaultTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "submitMove", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;
}

export namespace FeesWithdrawnEvent {
  export type InputTuple = [recipient: AddressLike, amount: BigNumberish];
  export type OutputTuple = [recipient: string, amount: bigint];
  export interface OutputObject {
    recipient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameCancelledEvent {
  export type InputTuple = [gameId: BytesLike];
  export type OutputTuple = [gameId: string];
  export interface OutputObject {
    gameId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameDrawEvent {
  export type InputTuple = [gameId: BytesLike, move: BigNumberish];
  export type OutputTuple = [gameId: string, move: bigint];
  export interface OutputObject {
    gameId: string;
    move: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameOpenedEvent {
  export type InputTuple = [
    gameId: BytesLike,
    initiator: AddressLike,
    stake: BigNumberish
  ];
  export type OutputTuple = [gameId: string, initiator: string, stake: bigint];
  export interface OutputObject {
    gameId: string;
    initiator: string;
    stake: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameSettledEvent {
  export type InputTuple = [
    gameId: BytesLike,
    winner: AddressLike,
    player1Move: BigNumberish,
    player2Move: BigNumberish,
    payout: BigNumberish,
    feeAdded: BigNumberish
  ];
  export type OutputTuple = [
    gameId: string,
    winner: string,
    player1Move: bigint,
    player2Move: bigint,
    payout: bigint,
    feeAdded: bigint
  ];
  export interface OutputObject {
    gameId: string;
    winner: string;
    player1Move: bigint;
    player2Move: bigint;
    payout: bigint;
    feeAdded: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameTimedOutEvent {
  export type InputTuple = [gameId: BytesLike];
  export type OutputTuple = [gameId: string];
  export interface OutputObject {
    gameId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MoveSubmittedEvent {
  export type InputTuple = [
    gameId: BytesLike,
    player: AddressLike,
    move: BigNumberish
  ];
  export type OutputTuple = [gameId: string, player: string, move: bigint];
  export interface OutputObject {
    gameId: string;
    player: string;
    move: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TimeoutUpdatedEvent {
  export type InputTuple = [newTimeout: BigNumberish];
  export type OutputTuple = [newTimeout: bigint];
  export interface OutputObject {
    newTimeout: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RockPaperScissors extends BaseContract {
  connect(runner?: ContractRunner | null): RockPaperScissors;
  waitForDeployment(): Promise<this>;

  interface: RockPaperScissorsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  cancel: TypedContractMethod<[gameId: BytesLike], [void], "nonpayable">;

  claimTimeout: TypedContractMethod<[gameId: BytesLike], [void], "nonpayable">;

  defaultTimeout: TypedContractMethod<[], [bigint], "view">;

  feePool: TypedContractMethod<[], [bigint], "view">;

  getGame: TypedContractMethod<
    [gameId: BytesLike],
    [RockPaperScissors.GameStructOutput],
    "view"
  >;

  maxBet: TypedContractMethod<[], [bigint], "view">;

  minBet: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setDefaultTimeout: TypedContractMethod<
    [newTimeout: BigNumberish],
    [void],
    "nonpayable"
  >;

  submitMove: TypedContractMethod<
    [gameId: BytesLike, move: BigNumberish],
    [void],
    "payable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawFees: TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "cancel"
  ): TypedContractMethod<[gameId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimTimeout"
  ): TypedContractMethod<[gameId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "defaultTimeout"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "feePool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getGame"
  ): TypedContractMethod<
    [gameId: BytesLike],
    [RockPaperScissors.GameStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "maxBet"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minBet"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDefaultTimeout"
  ): TypedContractMethod<[newTimeout: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitMove"
  ): TypedContractMethod<
    [gameId: BytesLike, move: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawFees"
  ): TypedContractMethod<
    [recipient: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "FeesWithdrawn"
  ): TypedContractEvent<
    FeesWithdrawnEvent.InputTuple,
    FeesWithdrawnEvent.OutputTuple,
    FeesWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "GameCancelled"
  ): TypedContractEvent<
    GameCancelledEvent.InputTuple,
    GameCancelledEvent.OutputTuple,
    GameCancelledEvent.OutputObject
  >;
  getEvent(
    key: "GameDraw"
  ): TypedContractEvent<
    GameDrawEvent.InputTuple,
    GameDrawEvent.OutputTuple,
    GameDrawEvent.OutputObject
  >;
  getEvent(
    key: "GameOpened"
  ): TypedContractEvent<
    GameOpenedEvent.InputTuple,
    GameOpenedEvent.OutputTuple,
    GameOpenedEvent.OutputObject
  >;
  getEvent(
    key: "GameSettled"
  ): TypedContractEvent<
    GameSettledEvent.InputTuple,
    GameSettledEvent.OutputTuple,
    GameSettledEvent.OutputObject
  >;
  getEvent(
    key: "GameTimedOut"
  ): TypedContractEvent<
    GameTimedOutEvent.InputTuple,
    GameTimedOutEvent.OutputTuple,
    GameTimedOutEvent.OutputObject
  >;
  getEvent(
    key: "MoveSubmitted"
  ): TypedContractEvent<
    MoveSubmittedEvent.InputTuple,
    MoveSubmittedEvent.OutputTuple,
    MoveSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TimeoutUpdated"
  ): TypedContractEvent<
    TimeoutUpdatedEvent.InputTuple,
    TimeoutUpdatedEvent.OutputTuple,
    TimeoutUpdatedEvent.OutputObject
  >;

  filters: {
    "FeesWithdrawn(address,uint256)": TypedContractEvent<
      FeesWithdrawnEvent.InputTuple,
      FeesWithdrawnEvent.OutputTuple,
      FeesWithdrawnEvent.OutputObject
    >;
    FeesWithdrawn: TypedContractEvent<
      FeesWithdrawnEvent.InputTuple,
      FeesWithdrawnEvent.OutputTuple,
      FeesWithdrawnEvent.OutputObject
    >;

    "GameCancelled(bytes32)": TypedContractEvent<
      GameCancelledEvent.InputTuple,
      GameCancelledEvent.OutputTuple,
      GameCancelledEvent.OutputObject
    >;
    GameCancelled: TypedContractEvent<
      GameCancelledEvent.InputTuple,
      GameCancelledEvent.OutputTuple,
      GameCancelledEvent.OutputObject
    >;

    "GameDraw(bytes32,uint8)": TypedContractEvent<
      GameDrawEvent.InputTuple,
      GameDrawEvent.OutputTuple,
      GameDrawEvent.OutputObject
    >;
    GameDraw: TypedContractEvent<
      GameDrawEvent.InputTuple,
      GameDrawEvent.OutputTuple,
      GameDrawEvent.OutputObject
    >;

    "GameOpened(bytes32,address,uint256)": TypedContractEvent<
      GameOpenedEvent.InputTuple,
      GameOpenedEvent.OutputTuple,
      GameOpenedEvent.OutputObject
    >;
    GameOpened: TypedContractEvent<
      GameOpenedEvent.InputTuple,
      GameOpenedEvent.OutputTuple,
      GameOpenedEvent.OutputObject
    >;

    "GameSettled(bytes32,address,uint8,uint8,uint256,uint256)": TypedContractEvent<
      GameSettledEvent.InputTuple,
      GameSettledEvent.OutputTuple,
      GameSettledEvent.OutputObject
    >;
    GameSettled: TypedContractEvent<
      GameSettledEvent.InputTuple,
      GameSettledEvent.OutputTuple,
      GameSettledEvent.OutputObject
    >;

    "GameTimedOut(bytes32)": TypedContractEvent<
      GameTimedOutEvent.InputTuple,
      GameTimedOutEvent.OutputTuple,
      GameTimedOutEvent.OutputObject
    >;
    GameTimedOut: TypedContractEvent<
      GameTimedOutEvent.InputTuple,
      GameTimedOutEvent.OutputTuple,
      GameTimedOutEvent.OutputObject
    >;

    "MoveSubmitted(bytes32,address,uint8)": TypedContractEvent<
      MoveSubmittedEvent.InputTuple,
      MoveSubmittedEvent.OutputTuple,
      MoveSubmittedEvent.OutputObject
    >;
    MoveSubmitted: TypedContractEvent<
      MoveSubmittedEvent.InputTuple,
      MoveSubmittedEvent.OutputTuple,
      MoveSubmittedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TimeoutUpdated(uint40)": TypedContractEvent<
      TimeoutUpdatedEvent.InputTuple,
      TimeoutUpdatedEvent.OutputTuple,
      TimeoutUpdatedEvent.OutputObject
    >;
    TimeoutUpdated: TypedContractEvent<
      TimeoutUpdatedEvent.InputTuple,
      TimeoutUpdatedEvent.OutputTuple,
      TimeoutUpdatedEvent.OutputObject
    >;
  };
}
